tls:
  certificates:
    - certFile: /letsencrypt/5407970b958b955a42350feb9fd4ff1c5da15dc88e95453c2c5c06809b188d0a.pem
      keyFile: /letsencrypt/5407970b958b955a42350feb9fd4ff1c5da15dc88e95453c2c5c06809b188d0a-key.pem
      stores:
        - default
    - certFile: /letsencrypt/ad68e4ae189aa142e92c4050f8b4034a80c60dfc2be4e5b794ad1c75ab93f6bf.pem
      keyFile: /letsencrypt/ad68e4ae189aa142e92c4050f8b4034a80c60dfc2be4e5b794ad1c75ab93f6bf-key.pem
      stores:
        - default
    - certFile: /letsencrypt/adc5fede12f4b8eb0c955caf02855740579d23665fd977543d56c45bb5cfeb48.pem
      keyFile: /letsencrypt/adc5fede12f4b8eb0c955caf02855740579d23665fd977543d56c45bb5cfeb48-key.pem
      stores:
        - default
